### ISSUE TITLE
Ownership Issues

### ISSUE THREAD

**Issue by spar36** [eccabay/A1_part2#10]
You defined the queue constructor to take in an Object* as well as push to take in a object*.

As per lecture, this means that the queue now takes ownership of those objects. So when the queue is deleted, it needs to delete the objects it stores. As well, when the queue is cleared, it is responsible for deleting the internal objects.

Right now your test cases segfault because you are clearing multiple queues that share objects, hence a double freeing the internal string objects.

**Comment by eccabay** [comment]
I've updated the tests so they at least shouldn't segfault, but without the implementation I'm not sure if they're perfect. I won't close this issue yet, if there are more testing issues please let me know.

**Comment by spar36** [comment]
I just ran it with my implementation and it works.
You are still adding the same objects to both q2 and q3 (line 46 and 47), but you then pop them before before calling clear ,so all good.

There are some more memory issues with the tests, but i will open up a separate issue.
